version: "3.8"
services:
  backend:
    build: .
    ports:
      - "8090:8080"
    env_file:
      - .env
    depends_on:
      - db
    environment:
      DATABASE_URL: postgres://postgres:${POSTGRES_PASSWORD}@db/safechat
      TZ: Europe/Brussels
  db:
    image: postgres:16
    restart: always
    environment:
      POSTGRES_DB: safechat
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      TZ: Europe/Brussels
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
volumes:
  pgdata:
